### ISSUE TITLE
Shorting raws by "selected_by_percent" criteria doesn't work as expected

### ISSUE THREAD

**Issue by geo-xar** [ilias4780/fpl_statistics_ui_app#3]
**Observations:**
Numbers from 9 to 0 are shorted correctly
There is a persistent shorting issue with double-digit numbers i.e. 35%

**The issue in more details:**
When there is a double-digit percentage then it is shorted based on its first digit i.e 35% is shorted based on digit 3
As a result, the list contains percentages in the following order:
45%
4.3%
36%
3.2%
29%
2,0%

**Solution:**
Numbers should be converted from string to doubles and then shorted correctly no matter how many digits they have.

**Comment by ilias4780** [comment]
Fix will be included in next version, 1.7.0.

**Comment by ilias4780** [comment]
Version 1.7.0 pushed.
