### ISSUE TITLE
Will like to change the GUI

### ISSUE THREAD

**Issue by HanslettTheDev** [ilias4780/fpl_statistics_ui_app#7]
Functionality is working pretty well. I will make some adjustments to the ui

**Comment by ilias4780** [comment]
Hello @HanslettTheDev, are you going to proceed with ui changes or suggest any? Otherwise, I will close this issue.

**Comment by HanslettTheDev** [comment]
YOU CAN CLOSE IT BUT I WILL STILL MAKE THE NEEDED CHANges

**Comment by ilias4780** [comment]
Ok, thank you!

**Comment by ilias4780** [comment]
Hello mate,

No problem at all, feel free to meddle with it.

Kind regards,
Ilias

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Hanslett ***@***.***>
Sent: Saturday, March 26, 2022 6:40:56 PM
To: ilias4780/fpl_statistics_ui_app ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ilias4780/fpl_statistics_ui_app] Will like to change the GUI (Issue #7)


Functionality is working pretty well. I will make some adjustments to the ui
